import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

df_raw = pd.read_csv('911.csv')
df = pd.DataFrame(df_raw)
print(df.info())
value_counts = df['zip'].value_counts()
print(value_counts.head(5))
town_ship = df['twp'].value_counts()
print(town_ship.head(5))
title_unique = df['title'].nunique()
print(title_unique)
df['Reason'] = df['title'].apply(lambda x: x.split(':')[0])
print(df.head(2))
common_reason = df['Reason'].value_counts()
print(common_reason.head(3))
sb.countplot(x = 'Reason',data = df)
plt.show()
df['timeStamp'] = pd.to_datetime(df['timeStamp'])
print(type(df['timeStamp'].iloc[0]))
mani_neram = df['timeStamp'].iloc[0]
print(mani_neram.hour)
df['Hour'] = df['timeStamp'].apply(lambda x:x.hour)
df['Month'] = df['timeStamp'].apply(lambda x:x.month)
df['Days of week'] = df['timeStamp'].apply(lambda x: x.dayofweek)
print(df.head(5))
sb.countplot(x = 'Days of week',data = df, hue='Reason')
plt.show()
sb.countplot(x = 'Month', data = df, hue = 'Reason')
plt.show()
byMonth = df.groupby('Month').count()
print(byMonth.head(5))
byMonth['lat'].plot()
plt.show()
df['Date'] = df['timeStamp'].apply(lambda x: x.date())
print(df.head(5))
byDate = df.groupby('Date').count()
print(byDate.head(5))
byDate.plot()
plt.show()
df2=df.pivot_table(index = 'Hour',columns='Days of week')
sb.heatmap(df2,cmap='coolwarm')
plt.show()
sb.clustermap(df2,cmap = 'plasma')
plt.show()
df3 = df.pivot_table(index='Hour',columns='Month')
sb.clustermap(df3,cmap = 'coolwarm')
plt.show()
sb.clustermap(df3,cmap = 'plasma')
plt.show()


